version: '3'

services:
  kotlin-application-api:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - kotlin-application-db
    networks:
      - kotlin-application

  kotlin-application-db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '7000:5432'
    volumes:
      - /home/kastrowalker/projetcs/DATA_DOCKER:/var/lib/postgresql/data
    networks:
      - kotlin-application

networks:
  kotlin-application:
    driver: bridge